@extends('dashboard.layout')

@section('page_title', 'Security & Email Settings')

@section('styles')
<style>
    .settings-grid {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 30px;
    }

    @media(max-width: 900px) {
        .settings-grid {
            grid-template-columns: 1fr;
        }
    }

    .form-group {
        margin-bottom: 20px;
    }

    .form-group label {
        display: block;
        font-size: 0.85rem;
        font-weight: 600;
        color: var(--gray);
        margin-bottom: 8px;
    }

    .form-control {
        width: 100%;
        padding: 10px 14px;
        border-radius: 8px;
        border: 1px solid var(--border);
        background: rgba(255, 255, 255, 0.5);
        color: var(--dark);
        font-family: inherit;
        font-size: 0.9rem;
        outline: none;
        transition: var(--transition);
    }

    [data-theme="dark"] .form-control {
        background: rgba(0, 0, 0, 0.2);
    }

    .form-control:focus {
        border-color: var(--primary);
    }

    .checkbox-group {
        display: flex;
        flex-direction: column;
        gap: 15px;
        margin-bottom: 20px;
    }

    .checkbox-item {
        display: flex;
        align-items: flex-start;
        gap: 12px;
        cursor: pointer;
    }

    .checkbox-item input {
        margin-top: 3px;
        width: 16px;
        height: 16px;
        accent-color: var(--primary);
        cursor: pointer;
    }

    .checkbox-label-text {
        font-size: 0.9rem;
        font-weight: 600;
    }

    .checkbox-desc {
        font-size: 0.78rem;
        color: var(--gray);
        margin-top: 2px;
    }

    .totp-setup-container {
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 20px;
        padding: 20px;
        background: rgba(99, 102, 241, 0.05);
        border: 1px dashed var(--primary);
        border-radius: 12px;
        margin-top: 15px;
        text-align: center;
    }

    .totp-qr-wrapper {
        padding: 10px;
        background: white;
        border-radius: 8px;
        border: 1px solid var(--border);
    }

    .totp-secret-key {
        font-family: monospace;
        font-size: 1.1rem;
        font-weight: 700;
        background: rgba(0,0,0,0.03);
        padding: 6px 12px;
        border-radius: 6px;
        color: var(--primary);
        letter-spacing: 1px;
    }
</style>
@endsection

@section('content')
<div class="settings-grid">
    <!-- Left Column: Email Notification Settings -->
    <div class="card">
        <h3 style="font-size: 1.15rem; font-weight: 700; margin-bottom: 20px; color: var(--primary);">
            <i class="fa-solid fa-envelope" style="margin-right: 8px;"></i> Email Notification Preferences
        </h3>
        <p style="font-size: 0.85rem; color: var(--gray); margin-bottom: 25px; line-height: 1.5;">
            Toggle the automated system emails you wish to receive for events on your merchant profile.
        </p>

        <form action="{{ route('settings.security.notifications') }}" method="POST">
            @csrf

            <div class="checkbox-group">
                <!-- Created -->
                <label class="checkbox-item">
                    <input type="checkbox" name="notify_invoice_created" value="1" @if($user->notify_invoice_created) checked @endif>
                    <div>
                        <div class="checkbox-label-text">Invoice Creation</div>
                        <div class="checkbox-desc">Receive an email whenever a checkout invoice is generated by API or manually.</div>
                    </div>
                </label>

                <!-- Paid -->
                <label class="checkbox-item">
                    <input type="checkbox" name="notify_invoice_paid" value="1" @if($user->notify_invoice_paid) checked @endif>
                    <div>
                        <div class="checkbox-label-text">Invoice Payment Success</div>
                        <div class="checkbox-desc">Receive an email immediately when a transaction is completed and synced.</div>
                    </div>
                </label>

                <!-- Expired -->
                <label class="checkbox-item">
                    <input type="checkbox" name="notify_invoice_expired" value="1" @if($user->notify_invoice_expired) checked @endif>
                    <div>
                        <div class="checkbox-label-text">Invoice Expiration</div>
                        <div class="checkbox-desc">Receive an email when checkout sessions expire without payment matches.</div>
                    </div>
                </label>

                <!-- Login -->
                <label class="checkbox-item">
                    <input type="checkbox" name="notify_login" value="1" @if($user->notify_login) checked @endif>
                    <div>
                        <div class="checkbox-label-text">Account Logins</div>
                        <div class="checkbox-desc">Receive an email alert for every successful sign-in to your merchant profile.</div>
                    </div>
                </label>
            </div>

            <button type="submit" class="btn btn-primary" style="padding: 10px 24px;">
                <i class="fa-solid fa-floppy-disk"></i> Save Email Preferences
            </button>
        </form>
    </div>

    <!-- Right Column: Two-Factor Authentication Settings -->
    <div class="card">
        <h3 style="font-size: 1.15rem; font-weight: 700; margin-bottom: 20px; color: var(--primary);">
            <i class="fa-solid fa-shield-halved" style="margin-right: 8px;"></i> Two-Factor Authentication (2FA)
        </h3>
        <p style="font-size: 0.85rem; color: var(--gray); margin-bottom: 25px; line-height: 1.5;">
            Add an extra layer of protection to your merchant profile. Secure logins using OTP verification.
        </p>

        <form action="{{ route('settings.security.2fa') }}" method="POST">
            @csrf

            <div class="form-group">
                <label for="two_factor_method">Authentication Method</label>
                <select name="two_factor_method" id="two_factor_method" class="form-control" onchange="toggle2faFields(this.value)">
                    <option value="none" @if($user->two_factor_method === 'none') selected @endif>Disabled (Password Only)</option>
                    <option value="email" @if($user->two_factor_method === 'email') selected @endif>Email OTP (One-Time-Code via Inbox)</option>
                    <option value="totp" @if($user->two_factor_method === 'totp') selected @endif>Authenticator App (Google Authenticator / Authy)</option>
                </select>
            </div>

            <!-- TOTP Setup Fields -->
            <div id="totp-setup-section" style="display: @if($user->two_factor_method === 'totp') block @else none @endif;">
                <div class="totp-setup-container">
                    <p style="font-size: 0.82rem; color: var(--dark); line-height: 1.4; margin-bottom: 10px;">
                        1. Scan the QR code below or enter the secret key manually into your Authenticator App:
                    </p>
                    
                    <div class="totp-qr-wrapper">
                        <canvas id="totp-qr-canvas" style="width: 140px; height: 140px; display: block;"></canvas>
                    </div>

                    <div style="width: 100%;">
                        <div style="font-size: 0.75rem; color: var(--gray); margin-bottom: 5px; font-weight: 700;">Secret Key:</div>
                        <div class="totp-secret-key">{{ $totpSecret }}</div>
                        <input type="hidden" name="totp_secret" value="{{ $totpSecret }}">
                    </div>

                    <div style="width: 100%; border-top: 1px dashed var(--border); padding-top: 15px; margin-top: 5px; text-align: left;">
                        <p style="font-size: 0.82rem; color: var(--dark); line-height: 1.4; margin-bottom: 12px;">
                            2. Enter the 6-digit verification code from your Authenticator App to confirm the setup:
                        </p>
                        <input type="text" name="totp_code" id="totp_code" class="form-control" placeholder="000000" maxlength="6" style="text-align: center; font-size: 1.1rem; letter-spacing: 2px;">
                    </div>
                </div>
            </div>

            <button type="submit" class="btn btn-primary" style="padding: 10px 24px; margin-top: 20px; width: 100%;">
                <i class="fa-solid fa-shield-check"></i> Update Security Settings
            </button>
        </form>
    </div>
</div>
@endsection

@section('scripts')
<script src="{{ asset('js/qrious.min.js') }}"></script>
<script>
    function toggle2faFields(val) {
        const setupSection = document.getElementById('totp-setup-section');
        const codeInput = document.getElementById('totp_code');
        if (val === 'totp') {
            setupSection.style.display = 'block';
            codeInput.setAttribute('required', 'required');
            initializeQr();
        } else {
            setupSection.style.display = 'none';
            codeInput.removeAttribute('required');
        }
    }

    let qrInitialized = false;
    function initializeQr() {
        if (qrInitialized) return;
        const canvas = document.getElementById('totp-qr-canvas');
        if (canvas) {
            new QRious({
                element: canvas,
                value: "{!! $qrCodeUrl !!}",
                size: 200
            });
            qrInitialized = true;
        }
    }

    document.addEventListener('DOMContentLoaded', function() {
        if (document.getElementById('two_factor_method').value === 'totp') {
            initializeQr();
        }
    });
</script>
@endsection
